[package]
name = "predictionsmart"
edition = "2024.beta"
license = "MIT"
authors = ["PredictionSmart Team"]

[dependencies]
# Sui dependencies are auto-included in 2024.beta edition

# Pyth Oracle - Price feeds (Testnet)
[dependencies.Pyth]
git = "https://github.com/pyth-network/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "sui-contract-testnet"

[dependencies.Wormhole]
git = "https://github.com/wormhole-foundation/wormhole.git"
subdir = "sui/wormhole"
rev = "sui/testnet"

# Switchboard Oracle - On-demand feeds (Testnet)
[dependencies.Switchboard]
git = "https://github.com/switchboard-xyz/sui.git"
subdir = "on_demand/"
rev = "testnet"

[addresses]
predictionsmart = "0x0"

[dev-dependencies]

[dev-addresses]
